config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  post 'pages/home'
  root to: 'pages#home'
  post "/" => "pages#home"
  get 'pages/bad_ingredients'
  get 'pages/about'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @ingredients = params[:ingredients]
    @uniqFoundIngredients = getScanResult(@ingredients)
    if !@ingredients.blank?
      if  !@uniqFoundIngredients.any?
      flash.now[:success] = "Item does not contain any common harmful ingredients"
      
    else
      message = "Item contains "
      @uniqFoundIngredients.each {|ingredients| message << " #{ingredients}, "}
      if message[-2]=  ','
         message[-2]= ''
      end
      flash.now[:danger] = message
    end
    end
    
  end
  def bad_ingredient
    
  end
  
  def about 
  end
  private
  def getScanResult(ingredients)
    @badSulfates = ["Alkylbenzene Sulfonate","Alkyl Benzene Sulfonate","Ammonium Laureth Sulfate","Ammonium Lauryl Sulfate","Ammonium Xylenesulfonate",
      "Sodium C14-16 Olefin Sulfonate","Sodium Cocoyl Sarcosinate","Sodium Laureth Sulfate","Sodium Lauryl Sulfate","Sodium Lauryl Sulfoacetate",
      "Sodium Myreth Sulfate","Sodium Xylenesulfonate","TEA-dodecylbenzenesulfonate","Ethyl PEG-15 Cocamine Sulfate","Dioctyl Sodium Sulfosuccinate"]
    @badSilicones = ["Dimethicone","Bis-aminopropyl Dimethicone","Cetearyl Methicone","Cetyl Dimethicone","Cyclopentasiloxane","Stearoxy Dimethicone",
      "Stearyl Dimethicone","Trimethylsilylamodimethicone","Amodimethicone","Dimethicone","Dimethiconol","Behenoxy Dimethicone","Phenyl Trimethicone"]
    @badAlcohols = ["Denatured Alcohol","SD Alcohol 40","Witch Hazel","Isopropanol","Ethanol","SD alcohol","Propanol","Propyl Alcohol","Isopropyl Alcohol"]
    @otherBadIngredients = ["Mineral Oil","Paraffinum Liquidum","Petrolatum","Bees Wax","Candelilla Wax"]
    @foundIngredients = Array.new
    @uniqFoundIngredients = Array.new
    if(ingredients)
      ingredients.each_line do |line|
        @badSulfates.each do |ingredient|
          regex = /(^|\W)#{ingredient}($|\W)/i
          if line.match(regex) then @foundIngredients.push(ingredient)  end
        end
        @badSilicones.each do |ingredient|
          regex = /(^|\W)#{ingredient}($|\W)/i
          if line.match(regex) then @foundIngredients.push(ingredient)  end
        end
        @badAlcohols.each do |ingredient|
          regex = /(^|\W)#{ingredient}($|\W)/i
          if line.match(regex) then @foundIngredients.push(ingredient)  end
        end
        @otherBadIngredients.each do |ingredient|
          regex = /(^|\W)#{ingredient}($|\W)/i
          if line.match(regex) then @foundIngredients.push(ingredient)  end
         end
      end
    end
    
    @uniqFoundIngredients = @foundIngredients.uniq()
    return @uniqFoundIngredients
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_message.html.erb
<div class="row">
  <div class= "container">
    <% flash.each do |name,msg|  %>
      <div class= 'alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg,:id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
     <%end%>           
    
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Quirky Hairs",root_path, class:"navbar-brand", id:"logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav">
        <li><%= link_to "Home",pages_home_path%></li>
        <li><%= link_to "Ingredients",pages_bad_ingredients_path%></li>
        <li><%= link_to "About",pages_about_path%></li>
      </ul>
  
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
<head>
  <title>QuirkyHairs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation'%>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>
  About
</h1>

app/views/pages/bad_ingredients.html.erb
<h1>
  Bad ingredients
</h1>

app/views/pages/home.html.erb
<div class="container">
  <%= form_tag do %>
  <div class="form-group">
     <%=text_area_tag 'ingredients', @ingredients ,class:"form-control",id:"input_area",autofocus:true %>
  </div>
  <%=  submit_tag 'Scan',class:'btn btn-info btn-lg btn-submit'  %>
</div>
<% end %>
<div class = "container">
   <%= render 'layouts/message'%>
</div>